version: 0.2

env:
  secrets-manager:
    DISTRIBUTION_ID: Books:DISTRIBUTION_ID
    API_URL: Books:API_URL
    API_KEY: Books:API_KEY
    CERT_ARN: Books:CERT_ARN

phases:
  install:
    runtime-versions:
      nodejs: 22
    commands:
      - export PROJECT_NAME=Books
      - npm install --global yarn
  build:
    on-failure: RETRY-3
    commands:
      - chmod +x bash/makeConfig.sh
      - bash/makeConfig.sh
      - yarn
      - cd cdk
      - yarn
      - cd ..
      - yarn build
      - cd cdk
      - yarn build
      - yarn synth
      - yarn deploy
      - aws cloudfront create-invalidation --distribution-id $DISTRIBUTION_ID --paths "/*"
    finally:
      - echo Build completed on `date`
artifacts:
  files:
    - "**/*"
